<?php
include('config.php'); 
include('session.php'); 
if (ADVISOR_ID === 0)
	header('Location: ./login.php');
else {
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<title>adminhelp.php</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="./css/custom.css">
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans">
	<script> 
    $(function(){
      $("#includeHeader").load("header.html"); 
    });
    </script>
	<script> 
    $(function(){
      $("#includeNavbar").load("navbar.php"); 
    });
    </script>
	<script> 
    $(function(){
      $("#includeFooter").load("footer.html"); 
    });
    </script>
	<script>
	function validateForm()
	{
		var a=document.forms[instructorAddNewForm][instructorEmail].value;
		if (a==null || a=="")
		{
			alert("Email is a required field");
			return false;
		}
	}
	</script>
</head>
<body>
<div class="wrapper">
<div id="includeHeader"></div>
<div id="includeNavbar"></div>
<div class="content" align="center">
<table width="80%">
<tr>
<td>
<h3>Information about the website</h3>
<div align="center">
<table width="80%">
<tr>
<td>
<ul class="list-group">
<li class="list-group-item">
Tasks planned
<ol>
<li>Data needs to be updated</li>
<li>Auto assign roster based on enollment type (FT/PT)</li>
<li>Bulk upload of students planned</li>
<li>Adding grades for multiple students at a time - remaining</li>
</ol>
</li>
<li class="list-group-item">
<ul class="list-group">
<li class="list-group-item">
Student Statuses
<ul>
<li>0: Enrolled</li>
<li>1: Debarred</li>
<li>2: Dismissed</li>
<li>3: Dropped Out</li>
<li>4: Graduated</li>
</ul>
</li>
<li class="list-group-item">
Student Enrollment types
<ul>
<li>0: Full Time</li>
<li>1: Part Time</li>
</ul>
</li>
<li class="list-group-item">
Student Standing types
<ul>
<li>0: Good</li>
<li>1: Bad</li>
<li>2: Probation</li>
<li>3: Last Chance Probabtion</li>
</ul>
</li>
<li class="list-group-item">
<p>
Term Codes are unique and auto assigned by the system(Eg: 220181)
<br /><br />
The above Term Code can be understood as 2-2018-1. Where
<ul>
<li>2: Chicago campus</li>
<li>2018: Year</li>
<li>1: Month in which the semester (of the offered course) started [1: Spring/January; 5: Summer/May; 8: Fall/August]</li>
</ul>
</p>
</li>
</ul>
</li>
<li class="list-group-item">
The best way to go around in the database is as follows<br />
1. Add Instructors<br />
2. Create a course<br />
3. Create a course offering (CRN is not unique. Term Code is unique and is autogenerated.)<br />
4. Add a new student<br />
5. Add a grade. For this you need the course offering and the student in the system<br />
6. You can also add notes for a student. Select the student and then enter notes. You can also view notes there<br /><br />
<ul>
<li>You can also view/edit a course, the course offering, instructor, students, grade</li>
<li>Logging in to the system is important to maintain the session (development requirement).</li>
<li>Logs are maintained as well</li>
</ul>
</li>
</ul>
</td>
</tr>
</table>
</div>
</td>
</tr>
<tr>
<td><p>&nbsp;</p></td>
</tr>
</table>
</div>
<div class="push"></div>
</div>
<div id="includeFooter"></div>
</body>
</html>
<?php
$conn->close();
}
?>